Repository andela/ah-infinity-stones-frontend, pull requests merged in 2019-01, with the labels that each got.

#3 #161966866 Update TravisCI to run tests
  .travis.yml
  README.md
Labels: Ready

#6 #161966864 Setup testing environment
  package-lock.json
  package.json
  src/App.test.js
  src/__snapshots__/App.test.js.snap
  src/setupTests.js
Labels: Ready

#5 #161966869 Run Code Climate test coverage
  .travis.yml
  README.md
Labels: Ready

#2 #161966863 Install and Setup Redux
  package-lock.json
  package.json
  src/App.js
  src/App.jsx
  src/__snapshots__/App.test.js.snap
  src/components/Articles/Articles.jsx
  src/components/Comments/Comments.jsx
  src/components/Users/Users.jsx
  src/logo.svg
  src/redux/actions/actionTypes.js
  src/redux/actions/articleActions.js
  src/redux/reducers/articleReducer.js
  src/redux/reducers/index.js
  src/redux/sagas/incrementSaga.js
  src/redux/sagas/index.js
  src/redux/store.js
  src/static/css/index.css
  src/static/images/logo.png
Labels: Peer Review

#7 #163083409 Setup and deploy base application to Heroku
  Procfile
  static.json
Labels: Ready

#4 #161966868 Setup Sass Preprocessor
  bin/build-css
  bin/watch-css
  package-lock.json
  package.json
  public/css/font-awesome.min.css
  public/css/main.css
  public/css/materialdesignicons.min.css
  public/css/style_1.css
  public/css/style_2.css
  public/fonts/FontAwesome.otf
  public/fonts/fontawesome-webfont.eot
  public/fonts/fontawesome-webfont.svg
  public/fonts/fontawesome-webfont.ttf
  public/fonts/fontawesome-webfont.woff
  public/fonts/fontawesome-webfont.woff2
  public/fonts/materialdesignicons-webfont.eot
  public/fonts/materialdesignicons-webfont.svg
  public/fonts/materialdesignicons-webfont.ttf
  public/fonts/materialdesignicons-webfont.woff
  public/fonts/materialdesignicons-webfont.woff2
  src/App.css
  src/App.js
  src/__snapshots__/App.test.js.snap
  src/assets/css/main.scss
  src/assets/fonts/FontAwesome.otf
  src/assets/fonts/font-awesome.min.css
  src/assets/fonts/fontawesome-webfont.eot
  src/assets/fonts/fontawesome-webfont.svg
  src/assets/fonts/fontawesome-webfont.ttf
  src/assets/fonts/fontawesome-webfont.woff
  src/assets/fonts/fontawesome-webfont.woff2
  src/assets/fonts/materialdesignicons-webfont.eot
  src/assets/fonts/materialdesignicons-webfont.svg
  src/assets/fonts/materialdesignicons-webfont.ttf
  src/assets/fonts/materialdesignicons-webfont.woff
  src/assets/fonts/materialdesignicons-webfont.woff2
  src/assets/fonts/materialdesignicons.min.css
  src/index.js
  src/logo.svg
  src/static/css/index.css
  src/static/images/logo.png
Labels: Ready

#8 #163110966 Integrate houndCI to Github
  .eslintignore
  .eslintrc.js
  .hound.yml
  .scc-lint.yml
  README.md
  package-lock.json
  package.json
  src/setupTests.js
Labels: Ready

#11 #161966872 Implement User Login Feature
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/App.test.js
  src/__snapshots__/App.test.js.snap
  src/assets/css/main.scss
  src/common/constants.js
  src/components/Article/index.jsx
  src/components/Forms/LoginForm/LoginForm.scss
  src/components/Forms/LoginForm/index.jsx
  src/helpers/messages.js
  src/index.js
  src/redux/actions/actionTypes.js
  src/redux/actions/articleActions.js
  src/redux/actions/loginActions.js
  src/redux/reducers/articleReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/sagas/incrementSaga.js
  src/redux/sagas/index.js
  src/redux/sagas/loginSaga.js
  src/redux/store.js
  src/services/login.js
  src/views/Loader.jsx
  src/views/Login.jsx
  src/views/Login/Login.scss
  src/views/Login/Login.test.js
  src/views/Login/__snapshots__/Login.test.js.snap
  src/views/Login/index.jsx
  src/views/Navbar.jsx
Labels: Peer Review

#14 #161966873 Implement Social Login Feature
  .eslintrc.js
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Article/index.jsx
  src/components/Forms/LoginForm/LoginForm.scss
  src/components/Forms/LoginForm/index.jsx
  src/config/firebase.js
  src/helpers/socialAuthHelpers.js
  src/index.css
  src/redux/actions/__tests__/socialLoginActions.test.js
  src/redux/actions/actionTypes.js
  src/redux/actions/socialLoginActions.js
  src/redux/reducers/__tests__/socialLoginReducer.test.js
  src/redux/reducers/index.js
  src/redux/reducers/socialLoginReducer.js
  src/redux/sagas/index.js
  src/redux/sagas/socialLoginSaga.js
  src/serviceWorker.js
  src/services/socialAuth.js
  src/setupTests.js
  src/socialConfig.js.sample
  src/views/Login/Login.scss
  src/views/Login/Login.test.js
  src/views/Login/SocialLogin.jsx
  src/views/Login/__tests__/SocialLogin.test.js
  src/views/Login/__tests__/__snapshots__/SocialLogin.test.js.snap
  src/views/Navbar.jsx
Labels: WIP

#13 #161966871 Present user with a reset password link.
  .eslintrc.js
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/__snapshots__/App.test.js.snap
  src/components/Article/index.jsx
  src/components/Forms/LoginForm/LoginForm.scss
  src/components/Forms/LoginForm/index.jsx
  src/components/Forms/PasswordResetform/ResetPassword.scss
  src/components/Forms/PasswordResetform/Resetlink.jsx
  src/components/Forms/PasswordResetform/index.jsx
  src/components/Forms/tests/passwordReset.test.js
  src/components/User/ResetPassword/ResetLink.jsx
  src/components/User/ResetPassword/ResetPassword.scss
  src/components/User/ResetPassword/index.jsx
  src/components/User/ResetPassword/tests/PasswordRese.test.js
  src/components/User/ResetPassword/tests/ResetPassword.test.js
  src/components/User/ResetPassword/tests/__snapshots__/PasswordRese.test.js.snap
  src/components/User/ResetPassword/tests/__snapshots__/ResetPassword.test.js.snap
  src/redux/actions/actionTests/actionTests.test.js
  src/redux/actions/actionTypes.js
  src/redux/actions/articleActions.js
  src/redux/actions/passwordResetAction.js
  src/redux/reducers/index.js
  src/redux/reducers/passwordResetReducer.js
  src/redux/reducers/reducers tests/reducers.test.js
  src/redux/sagas/index.js
  src/redux/sagas/passworwordResetSagas.js
  src/services/passwordResetmail.js
  src/setupTests.js
  src/views/Home.jsx
  src/views/Login/Login.scss
  src/views/Login/Login.test.js
  src/views/Navbar.jsx
Labels: Peer Review

#21 feat(article-rating) : Fix article rating bug
  src/components/Article/index.jsx
Labels: Ready

#16 #161966874 User Profiles
  .eslintrc.js
  package-lock.json
  package.json
  src/App.jsx
  src/__snapshots__/App.test.js.snap
  src/assets/css/main.scss
  src/assets/images/loading_spinner.gif
  src/assets/images/spinner.gif
  src/assets/styles/main.scss
  src/components/Comments/Comments.scss
  src/components/Comments/index.jsx
  src/components/Profile/Profile.scss
  src/components/Profile/__snapshots__/profile.test.js.snap
  src/components/Profile/containers/Button.js
  src/components/Profile/containers/LoadingProfile.js
  src/components/Profile/containers/ProfileForm.js
  src/components/Profile/containers/ProfileItem.js
  src/components/Profile/index.jsx
  src/components/Profile/profile.test.js
  src/components/User/ResetPassword/tests/PasswordRese.test.js
  src/components/User/ResetPassword/tests/ResetPassword.test.js
  src/index.css
  src/index.js
  src/redux/actions/actionTypes.js
  src/redux/actions/profileActions.js
  src/redux/reducers/index.js
  src/redux/reducers/profileReducer.js
  src/redux/sagas/index.js
  src/redux/sagas/profileSagas.js
  src/services/profile.service.js
  src/views/Footer.jsx
  src/views/Login/Login.test.js
  src/views/Profile.jsx
  src/views/articles/allArticles.js
Labels: Peer Review

#22 #161966881 Implement article tags
  package.json
  public/index.html
  src/App.jsx
  src/__snapshots__/App.test.js.snap
  src/common/constants.js
  src/components/Article/Article.scss
  src/components/Article/Article.test.js
  src/components/Article/index.jsx
  src/components/Articles/ArticleByTags.jsx
  src/components/Articles/ArticleTags.scss
  src/components/Articles/Articles.test.js
  src/components/Articles/index.jsx
  src/components/Forms/ArticleForm/EditorToolbar.jsx
  src/components/Forms/ArticleForm/articleCreation.scss
  src/components/Forms/ArticleForm/index.jsx
  src/components/Forms/SignupForm/index.jsx
  src/components/Forms/articles/ArticleCreationForm/articleCreation.scss
  src/components/Forms/articles/ArticleCreationForm/articleCreation.scss~HEAD
  src/components/Forms/articles/ArticleCreationForm/index.jsx
  src/components/Forms/articles/ArticleCreationForm/index.jsx~HEAD
  src/components/Forms/articles/EditorToolbar.jsx
  src/components/Forms/articles/EditorToolbar.jsx~HEAD
  src/components/common/constants.js
  src/index.css
  src/redux/actions/actionTypes.js
  src/redux/actions/articleActions.js
  src/redux/reducers/articleTagsReducer.js
  src/redux/reducers/index.js
  src/redux/sagas/articleSaga.js
  src/redux/sagas/articleTagsSaga.js
  src/redux/sagas/index.js
  src/services/articleTags.js
  src/views/Footer.jsx
Labels: Peer Review

#23 #161966889 Display article read-time
  src/components/Article/Article.scss
  src/components/Article/index.jsx
Labels: Ready

#18 #161966882 share article on different platforms
  .env
  .eslintignore
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/components/Article/Article.test.js
  src/components/Article/index.jsx
  src/components/ArticleShare/shareArticle.js
  src/components/Articles/index.jsx
  src/components/Forms/SignupForm/index.jsx
  src/components/Forms/articles/ArticleCreationForm/ArticleCreation.test.js
  src/components/Forms/articles/ArticleCreationForm/articleCreation.scss
  src/components/Forms/articles/ArticleUpdateForm/ArticleUpdate.test.js
  src/components/Profile/containers/ProfileForm.js
  src/components/common/constants.js
  src/index.css
  src/redux/actions/articleActions.js
  src/redux/reducers/articleReducer.js
  src/redux/reducers/passwordResetReducer.js
  src/redux/reducers/reducers tests/reducers.test.js
  src/services/profile.service.js
  src/views/Navbar.jsx
  src/views/Signup/index.jsx
Labels: Peer Review

#25 #161966892: Readers can report an article
  src/components/Article/ReportArticle.js
  src/components/Article/ReportArticle.test.js
  src/components/Article/index.jsx
  src/redux/actions/actionTypes.js
  src/redux/actions/articleActions.js
  src/redux/sagas/articleSaga.js
  src/redux/sagas/index.js
  src/services/articlePayload.js
Labels: Ready

#26 #161966891 Bookmarks Listing
  .eslintrc.js
  .eslintrc.json
  package-lock.json
  src/App.jsx
  src/__snapshots__/App.test.js.snap
  src/components/Article/index.jsx
  src/components/Bookmark/index.jsx
  src/components/Profile/Profile.scss
  src/components/Profile/containers/Button.js
  src/index.css
  src/index.js
  src/redux/actions/__tests__/bookmarksActions.test.js
  src/redux/actions/actionTypes.js
  src/redux/actions/bookmarksActions.js
  src/redux/reducers/__tests__/bookmarksReducer.test.js
  src/redux/reducers/bookmarksReducer.js
  src/redux/reducers/index.js
  src/redux/sagas/__tests__/bookmarksSagas.test.js
  src/redux/sagas/bookmarksSagas.js
  src/redux/sagas/index.js
  src/services/__tests__/bookmarksService.test.js
  src/services/bookmarks.service.js
  src/views/Bookmarks/Bookmarks.scss
  src/views/Bookmarks/Bookmarks.test.js
  src/views/Bookmarks/__snapshots__/Bookmarks.test.js.snap
  src/views/Bookmarks/index.jsx
  src/views/Loader.jsx
  src/views/Login/index.jsx
Labels: Ready

#27 #161966888 Article filtering
  src/components/Article/Article.scss
  src/components/Article/Article.test.js
  src/components/Article/ArticleRating.test.js
  src/components/Article/index.jsx
  src/components/Articles/index.jsx
  src/components/Forms/SignupForm/index.jsx
  src/index.css
  src/redux/actions/actionTypes.js
  src/redux/actions/articleActions.js
  src/redux/reducers/articleReducer.js
  src/redux/sagas/articleSaga.js
  src/redux/sagas/index.js
  src/redux/sagas/searchArticleSaga.js
  src/services/articlePayload.js
  src/views/Navbar.jsx
  src/views/Search/__snapshots__/search.test.js.snap
  src/views/Search/index.jsx
  src/views/Search/search.test.js
  src/views/Signup/index.jsx
Labels: Ready

#28 #161966890 Implement article bookmarks feature
  package.json
  src/assets/css/main.scss
  src/components/Article/index.jsx
  src/components/Bookmark/__snapshots__/bookmark.test.js.snap
  src/components/Bookmark/bookmark.jsx
  src/components/Bookmark/bookmark.test.js
  src/components/Bookmark/bookmarks.scss
  src/redux/actions/__tests__/bookmarkActions.test.js
  src/redux/actions/actionTypes.js
  src/redux/actions/bookmarkActions.js
  src/redux/reducers/__tests__/bookmarkReducer.test.js
  src/redux/reducers/bookmarkReducer.js
  src/redux/reducers/index.js
  src/redux/sagas/bookmarkSaga.js
  src/redux/sagas/index.js
  src/services/__tests__/bookmark.test.js
  src/services/bookmark.js
Labels: Ready
